### ISSUE TITLE
Where is module ConfigParser?

### ISSUE THREAD

**Issue by ChijunZhang** [jcyk/Dynet-Biaffine-dependency-parser#3]
Thanks for this nice reimplement of Biaffine parser.
One question: where is the module file 'ConfigParser.py', it is required at line 1 of config.py:
`from ConfigParser import SafeConfigParser `

**Comment by jcyk** [comment]
FYI
https://docs.python.org/2/library/configparser.html

**Comment by ChijunZhang** [comment]
Thanks for the quick reply.
