### ISSUE TITLE
Why halved the batch size? 

### ISSUE THREAD

**Issue by hankcs** [jcyk/Dynet-Biaffine-dependency-parser#5]
Hi @jcyk , 

Thanks for your nice implementation, much cleaner than the TF codes, even produced higher scores.
On PTB-SD, better scores were reported:

```
This repo: LAS 95.01, UAS 96.05
TF repo:    LAS 94.81, UAS 95.89
```

I guess the reason is you halved the batch size:

https://github.com/jcyk/Dynet-Biaffine-dependency-parser/blob/903819b749e47f730ca5373d8c8a53aa068e08dd/run/train.py#L41

Is my understanding correct?
Thanks.

**Comment by jcyk** [comment]
That is just a trick I made to make it runnable. 
because when using the **old-version** Dynet, batch size 5000 is too big for GPU. My code computes the gradients by two passes, each with batch size 2500, and the results are averaged.

**Comment by jcyk** [comment]
You may find the difference by comparing the `train3000.py `and `train.py`

**Comment by hankcs** [comment]
Get it, nice trick. Thanks.
